username: "enzutjqdtdsqfo"
password: "8990b0cfebd7a6e8460193e4753775824800da9f73c8d5e8d47cccf9dfd6ca76"
host: "ec2-54-90-13-87.compute-1.amazonaws.com"
port: 5432
databaseName: "de7libtugc8ad0"

# username: "postgres"
# password: "root"
# host: "localhost"
# port: 5432
# databaseName: "dart_week
